language: python
sudo: false
python:
    - 2.7
    - 3.6
matrix:
   include:
     - python: 3.7
       dist: xenial
       sudo: true
install:
    - pip install tox-travis
script:
    - tox
notifications:
    email: false
